# Generated by Django 5.2.1 on 2025-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaro', '0019_auto_20160316_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='link',
            field=models.CharField(help_text='Link, unter dem der Text aufgerufen werden kann (ohne die Domain), zum Beispiel "/personen/mueller/otto/". Beginn und Ende "/", weitere "/" möglich; sonst nur a-z0-9. Keine Umlaute, Sonderzeichen, Leerzeichen, Satzzeichen außer ".".', max_length=50, unique=True),
        ),
    ]
