from django.urls import re_path

from .views import (
        NoteDetail, NoteList, PictureDetail, PictureList, PictureListUntagged,
        VideoDetail, VideoList,
        SourceDetail,
        DocumentList, DocumentDetail, SourceList,
        UnboundImagesView, CreateThumbnail,
        SetDateFromEXIF,
        SearchForDateRange,
        )


urlpatterns = (
        re_path(r'^all/$', NoteList.as_view(),
            name='note-list'),
        re_path(r'^sources/$', SourceList.as_view(),
            name='source-list'),
        re_path(r'^docs/$', DocumentList.as_view(),
            name='document-list'),
        re_path(r'^docs/(?P<order_by>\w+)/$',
            DocumentList.as_view(),
            name='document-list-ordered'),
        re_path(r'^source-view/(?P<pk>\d+)/$',
            SourceDetail.as_view(), name='source-detail'),
        re_path(r'^note-view/(?P<pk>\d+)/$',
            NoteDetail.as_view(), name='note-detail'),
        re_path(r'^doc-view/(?P<pk>\d+)/$',
            DocumentDetail.as_view(), name='document-detail'),
        re_path(r'^picture-view/(?P<pk>\d+)/$',
            PictureDetail.as_view(), name='picture-detail'),
        re_path(r'^video-view/(?P<pk>\d+)/$',
            VideoDetail.as_view(), name='video-detail'),
        re_path(r'^unbound-images/$',
            UnboundImagesView.as_view(), name='unbound-images'),
        re_path(r'^video-list/$',
            VideoList.as_view(), name='video-list'),
        re_path(r'^picture-list/$',
            PictureList.as_view(), name='picture-list'),
        re_path(r'^picture-list/(?P<size>\w+)/$',
            PictureList.as_view(), name='picture-list'),
        re_path(r'^picture-untagged/$',
            PictureListUntagged.as_view(), name='picture-list-untagged'),
        re_path(r'^picture-untagged/(?P<size>\w+)/$',
            PictureListUntagged.as_view(), name='picture-list-untagged'),
        re_path(r'^create-thumbnail/$',
            CreateThumbnail.as_view(),
            name='document-thumbnail'),
        re_path(r'^date-from-exif/(?P<pk>\d+)/$',
            SetDateFromEXIF.as_view(),
            name='set-date-from-exif'),
        re_path(r'^date-range/$',
            SearchForDateRange.as_view(),
            name='date-range'),
        re_path(r'^date-range/(?P<fr>\d+)/(?P<to>\d+)/' +
            r'(?P<undated>[YN])/$',
            SearchForDateRange.as_view(),
            name='date-range'),
        )


