# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20150407_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[(b'de', b'German')], default=b'de', max_length=10, verbose_name='Language'),
        ),
    ]
