# Generated by Django 2.1.13 on 2019-11-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20161228_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_profile', 'Can view profile'),)},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='codemirror_keymap',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'vim'), (2, 'sublime')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_on_comment_answer',
            field=models.BooleanField(default=False, verbose_name='Email-Benachrichtigung bei Antwort auf meine Kommentare'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_on_message',
            field=models.BooleanField(default=False, verbose_name='Email-Benachrichtigung bei Nachrichten'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'German')], default='de', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genealogio.Person'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='privacy',
            field=models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='closed', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time_zone',
            field=models.FloatField(choices=[(-12.0, '-12'), (-11.0, '-11'), (-10.0, '-10'), (-9.5, '-09.5'), (-9.0, '-09'), (-8.5, '-08.5'), (-8.0, '-08 PST'), (-7.0, '-07 MST'), (-6.0, '-06 CST'), (-5.0, '-05 EST'), (-4.0, '-04 AST'), (-3.5, '-03.5'), (-3.0, '-03 ADT'), (-2.0, '-02'), (-1.0, '-01'), (0.0, '00 GMT'), (1.0, '+01 CET'), (2.0, '+02'), (3.0, '+03'), (3.5, '+03.5'), (4.0, '+04'), (4.5, '+04.5'), (5.0, '+05'), (5.5, '+05.5'), (6.0, '+06'), (6.5, '+06.5'), (7.0, '+07'), (8.0, '+08'), (9.0, '+09'), (9.5, '+09.5'), (10.0, '+10'), (10.5, '+10.5'), (11.0, '+11'), (11.5, '+11.5'), (12.0, '+12'), (13.0, '+13'), (14.0, '+14')], default=3.0, verbose_name='Time zone'),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='role',
            field=models.IntegerField(choices=[(0, 'Benutzer'), (1, 'Redakteur'), (2, 'Administrator')], default=0),
        ),
    ]
