# Generated by Django 5.2.1 on 2025-05-25 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpe', models.CharField(choices=[('fam_a_d', 'Vorfahren und Nachkommen einer Familie')], max_length=10)),
                ('levels_up', models.IntegerField(default=2)),
                ('levels_down', models.IntegerField(default=3)),
                ('obj_id', models.IntegerField(blank=True, null=True, verbose_name='Zugeordnetes Objekt')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titel')),
                ('public', models.BooleanField(default=False, verbose_name='Verfügbar für andere Benutzer')),
                ('directory', models.CharField(blank=True, max_length=300)),
                ('render_status', models.CharField(blank=True, max_length=800, verbose_name='Status')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Autoren')),
                ('obj_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Typ des zugeordneten Objekts')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Familienbaum')),
            ],
        ),
    ]
