# Generated by Django 5.2.1 on 2025-05-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytrees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familytree',
            options={'verbose_name': 'Stammbaum', 'verbose_name_plural': 'Stammbäume'},
        ),
    ]
