# Generated by Django 5.2.1 on 2025-05-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytrees', '0002_alter_familytree_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytree',
            name='black_white',
            field=models.BooleanField(default=False, help_text='Bilder nach scharz/weiß konvertieren'),
        ),
        migrations.AddField(
            model_name='familytree',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familytree',
            name='papersize',
            field=models.CharField(choices=[('auto', 'Automatisch berechnete Länge/Breite'), ('a4', 'DIN A4'), ('a3', 'DIN A3'), ('a2', 'DIN A2'), ('a1', 'DIN A1'), ('a0', 'DIN A0'), ('custom', 'Länge/Breite in mm')], default='auto'),
        ),
        migrations.AddField(
            model_name='familytree',
            name='resize_image_files',
            field=models.IntegerField(default=0, help_text='Skaliere Bilddateien (Breite in Pixeln; 0 = Dateien nicht verändern)'),
        ),
        migrations.AddField(
            model_name='familytree',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
