# Generated by Django 5.2.1 on 2025-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytrees', '0003_familytree_black_white_familytree_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytree',
            name='black_white',
            field=models.BooleanField(default=False, help_text='Bilder nach schwarz/weiß konvertieren'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='height',
            field=models.IntegerField(default=0, help_text='Höhe'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='papersize',
            field=models.CharField(choices=[('auto', 'Automatisch berechnete Länge/Breite'), ('a4', 'DIN A4'), ('a3', 'DIN A3'), ('a2', 'DIN A2'), ('a1', 'DIN A1'), ('a0', 'DIN A0'), ('custom', 'Länge/Breite in mm')], default='a3', help_text='Papierformat'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='resize_image_files',
            field=models.IntegerField(default=0, help_text='Skaliere Bilddateien (Breite in Pixeln; 0 = Automatisch anhand Papierformat)'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='width',
            field=models.IntegerField(default=0, help_text='Breite'),
        ),
    ]
