# Generated by Django 5.2.1 on 2025-05-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytrees', '0004_alter_familytree_black_white_alter_familytree_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytree',
            name='black_white',
            field=models.BooleanField(default=False, help_text='Bilder nach schwarz/weiß konvertieren', verbose_name='Schwarz/Weiß?'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='height',
            field=models.IntegerField(default=0, help_text='Nur für Papierformat Manuell', verbose_name='Höhe'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='levels_down',
            field=models.IntegerField(default=3, verbose_name='Nachkommen-Ebenen'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='levels_up',
            field=models.IntegerField(default=2, verbose_name='Vorfahren-Ebenen'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='papersize',
            field=models.CharField(choices=[('auto', 'Automatisch berechnete Länge/Breite'), ('a4', 'DIN A4'), ('a3', 'DIN A3'), ('a2', 'DIN A2'), ('a1', 'DIN A1'), ('a0', 'DIN A0'), ('custom', 'Manuell, Länge/Breite in mm')], default='a3', verbose_name='Papierformat'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='resize_image_files',
            field=models.IntegerField(default=0, help_text='Breite in Pixeln; 0 = Automatisch anhand Papierformat', verbose_name='Bilddateien skalieren?'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='tpe',
            field=models.CharField(choices=[('fam_a_d', 'Vorfahren und Nachkommen einer Familie')], default='fam_a_d', max_length=10, verbose_name='Art des Stammbaums'),
        ),
        migrations.AlterField(
            model_name='familytree',
            name='width',
            field=models.IntegerField(default=0, help_text='Nur für Papierformat Manuell', verbose_name='Breite'),
        ),
    ]
