# Generated by Django 5.2.1 on 2025-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytrees', '0005_alter_familytree_black_white_alter_familytree_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytree',
            name='preview_img',
            field=models.CharField(blank=True, default='preview', max_length=15),
        ),
    ]
