# Generated by Django 2.1.13 on 2019-11-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogio', '0026_auto_20161228_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.Place', verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='family',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_ref', to='genealogio.Person', verbose_name='Vater'),
        ),
        migrations.AlterField(
            model_name='family',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_ref', to='genealogio.Person', verbose_name='Mutter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='portrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notaro.Picture', verbose_name='Portrait'),
        ),
    ]
